FROM fedora:latest
 
RUN dnf -y update
RUN dnf -y install git gcc passwd python-virtualenv
RUN dnf -y install redhat-rpm-config python3-devel owfs-devel
RUN dnf clean all

# add user
RUN groupadd -r testUser
RUN useradd --create-home -r -g testUser testUser
RUN passwd -d testUser
 
USER testUser
WORKDIR /home/testUser

RUN git clone https://github.com/labgrid-project/labgrid
WORKDIR labgrid/

RUN virtualenv -p python3 venv
RUN . venv/bin/activate && python setup.py install
RUN ./venv/bin/pip install autobahn
RUN ./venv/bin/labgrid-client --help
RUN ./venv/bin/labgrid-exporter --help
